// Copyright 2023 The MediaPipe Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.mediapipe.tasks.vision.poselandmarker;

import com.google.auto.value.AutoValue;
import com.google.mediapipe.formats.proto.LandmarkProto;
import com.google.mediapipe.framework.image.MPImage;
import com.google.mediapipe.tasks.components.containers.NormalizedLandmark;
import com.google.mediapipe.tasks.components.containers.NormalizedRect;
import com.google.mediapipe.tasks.core.TaskResult;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

/** Represents the pose landmarks deection results generated by {@link PoseLandmarker}. */
@AutoValue
public abstract class PoseLandmarkerResult implements TaskResult {

  /** Coordinates and visibility only; no optional confidence or mask payloads. */
  public static final class Landmark {
    private final float x, y, z, visibility;

    private Landmark(float x, float y, float z, float visibility) {
      this.x = x;
      this.y = y;
      this.z = z;
      this.visibility = visibility;
    }

    public static Landmark create(float x, float y, float z, float visibility) {
      return new Landmark(x, y, z, visibility);
    }

    public float x() { return x; }
    public float y() { return y; }
    public float z() { return z; }
    public float visibility() { return visibility; }
  }

  /**
   * Result of the landmarks-only video API. Image coordinates are normalized; world coordinates
   * are body-relative meters. Rectangles use the same source coordinate system as image landmarks.
   */
  public static final class LandmarksOnlyResult implements TaskResult {
    private final long timestampMs;
    private final List<List<Landmark>> landmarks;
    private final List<List<Landmark>> worldLandmarks;
    private final List<NormalizedRect> poseRectsNextFrame;
    private final boolean poseDetectorRan;

    private LandmarksOnlyResult(long timestampMs, List<List<Landmark>> landmarks,
        List<List<Landmark>> worldLandmarks, List<NormalizedRect> poseRectsNextFrame,
        boolean poseDetectorRan) {
      this.timestampMs = timestampMs;
      this.landmarks = Collections.unmodifiableList(landmarks);
      this.worldLandmarks = Collections.unmodifiableList(worldLandmarks);
      this.poseRectsNextFrame = Collections.unmodifiableList(poseRectsNextFrame);
      this.poseDetectorRan = poseDetectorRan;
    }

    static LandmarksOnlyResult create(
        List<LandmarkProto.NormalizedLandmarkList> imageProtos,
        List<LandmarkProto.LandmarkList> worldProtos,
        List<com.google.mediapipe.formats.proto.RectProto.NormalizedRect> rectProtos,
        boolean detectorRan, long timestampMs) {
      List<List<Landmark>> imagePoses = new ArrayList<>(imageProtos.size());
      for (LandmarkProto.NormalizedLandmarkList pose : imageProtos) {
        List<Landmark> landmarks = new ArrayList<>(pose.getLandmarkCount());
        for (LandmarkProto.NormalizedLandmark landmark : pose.getLandmarkList()) {
          landmarks.add(Landmark.create(landmark.getX(), landmark.getY(), landmark.getZ(),
              landmark.getVisibility()));
        }
        imagePoses.add(Collections.unmodifiableList(landmarks));
      }
      List<List<Landmark>> worldPoses = new ArrayList<>(worldProtos.size());
      for (LandmarkProto.LandmarkList pose : worldProtos) {
        List<Landmark> landmarks = new ArrayList<>(pose.getLandmarkCount());
        for (LandmarkProto.Landmark landmark : pose.getLandmarkList()) {
          landmarks.add(Landmark.create(landmark.getX(), landmark.getY(), landmark.getZ(),
              landmark.getVisibility()));
        }
        worldPoses.add(Collections.unmodifiableList(landmarks));
      }
      List<NormalizedRect> rects = new ArrayList<>(rectProtos.size());
      for (com.google.mediapipe.formats.proto.RectProto.NormalizedRect rect : rectProtos) {
        rects.add(NormalizedRect.createFromProto(rect));
      }
      return new LandmarksOnlyResult(timestampMs, imagePoses, worldPoses, rects, detectorRan);
    }

    @Override public long timestampMs() { return timestampMs; }
    public List<List<Landmark>> landmarks() { return landmarks; }
    public List<List<Landmark>> worldLandmarks() { return worldLandmarks; }
    public List<NormalizedRect> poseRectsNextFrame() { return poseRectsNextFrame; }
    public boolean poseDetectorRan() { return poseDetectorRan; }
  }

  /**
   * Creates a {@link PoseLandmarkerResult} instance from the lists of landmarks and
   * segmentationMask protobuf messages.
   *
   * @param landmarksProto a List of {@link NormalizedLandmarkList}
   * @param worldLandmarksProto a List of {@link LandmarkList}
   * @param poseRectsNextFrameProto a List of normalized pose rectangles calculated for the next
   *     video frame
   * @param poseDetectorRan whether the pose detector graph ran for this frame
   * @param segmentationMasksData a List of {@link MPImage}
   */
  static PoseLandmarkerResult create(
      List<LandmarkProto.NormalizedLandmarkList> landmarksProto,
      List<LandmarkProto.LandmarkList> worldLandmarksProto,
      List<com.google.mediapipe.formats.proto.RectProto.NormalizedRect>
          poseRectsNextFrameProto,
      boolean poseDetectorRan,
      Optional<List<MPImage>> segmentationMasksData,
      long timestampMs) {

    Optional<List<MPImage>> multiPoseSegmentationMasks = Optional.empty();
    if (segmentationMasksData.isPresent()) {
      multiPoseSegmentationMasks =
          Optional.of(Collections.unmodifiableList(segmentationMasksData.get()));
    }

    List<List<NormalizedLandmark>> multiPoseLandmarks = new ArrayList<>();
    for (LandmarkProto.NormalizedLandmarkList handLandmarksProto : landmarksProto) {
      List<NormalizedLandmark> poseLandmarks =
          NormalizedLandmark.createListFromProto(handLandmarksProto);
      multiPoseLandmarks.add(Collections.unmodifiableList(poseLandmarks));
    }

    List<List<com.google.mediapipe.tasks.components.containers.Landmark>> multiPoseWorldLandmarks = new ArrayList<>();
    for (LandmarkProto.LandmarkList poseWorldLandmarksProto : worldLandmarksProto) {
      List<com.google.mediapipe.tasks.components.containers.Landmark> poseWorldLandmarks =
          com.google.mediapipe.tasks.components.containers.Landmark.createListFromProto(poseWorldLandmarksProto);
      multiPoseWorldLandmarks.add(Collections.unmodifiableList(poseWorldLandmarks));
    }

    List<NormalizedRect> poseRectsNextFrame = new ArrayList<>();
    for (com.google.mediapipe.formats.proto.RectProto.NormalizedRect rectProto :
        poseRectsNextFrameProto) {
      poseRectsNextFrame.add(NormalizedRect.createFromProto(rectProto));
    }

    return new AutoValue_PoseLandmarkerResult(
        timestampMs,
        Collections.unmodifiableList(multiPoseLandmarks),
        Collections.unmodifiableList(multiPoseWorldLandmarks),
        Collections.unmodifiableList(poseRectsNextFrame),
        poseDetectorRan,
        multiPoseSegmentationMasks);
  }

  static PoseLandmarkerResult create(
      List<LandmarkProto.NormalizedLandmarkList> landmarksProto,
      List<LandmarkProto.LandmarkList> worldLandmarksProto,
      Optional<List<MPImage>> segmentationMasksData,
      long timestampMs) {
    return create(
        landmarksProto,
        worldLandmarksProto,
        Collections.emptyList(),
        false,
        segmentationMasksData,
        timestampMs);
  }

  @Override
  public abstract long timestampMs();

  /** Pose landmarks of detected poses. */
  public abstract List<List<NormalizedLandmark>> landmarks();

  /** Pose landmarks in world coordinates of detected poses. */
  public abstract List<List<com.google.mediapipe.tasks.components.containers.Landmark>> worldLandmarks();

  /**
   * Normalized, expanded pose rectangles calculated for landmark detection on the next video
   * frame.
   *
   * <p>These rectangles can be supplied to {@link PoseLandmarker#detectForVideo(MPImage,
   * NormalizedRect, long)} so multiple landmarker instances can share one tracking state.
   */
  public abstract List<NormalizedRect> poseRectsNextFrame();

  /**
   * Whether the full-image pose detector graph ran for this frame.
   *
   * <p>A false value means MediaPipe skipped pose identification and sent an existing tracking
   * rectangle directly to landmark inference. This is execution telemetry, not a statement about
   * whether landmarks were present.
   */
  public abstract boolean poseDetectorRan();

  /** Pose segmentation masks. */
  public abstract Optional<List<MPImage>> segmentationMasks();
}
